const fs = require('fs');
const content = [
  'export const lightColors = {',
  '  primary: \'#1565C0\',',
  '  primaryDark: \'#0D47A1\',',
  '  primaryLight: \'#E3F2FD\',',
  '  accent: \'#FF6D00\',',
  '  background: \'#F5F7FA\',',
  '  card: \'#FFFFFF\',',
  '  surface: \'#FFFFFF\',',
  '',
  '  textPrimary: \'#1F2937\',',
  '  textSecondary: \'#6B7280\',',
  '  textLight: \'#9CA3AF\',',
  '',
  '  border: \'#E5E7EB\',',
  '  divider: \'#F3F4F6\',',
  '',
  '  success: \'#10B981\',',
  '  successLight: \'#D1FAE5\',',
  '  warning: \'#F59E0B\',',
  '  warningLight: \'#FEF3C7\',',
  '  danger: \'#EF4444\',',
  '  dangerLight: \'#FEE2E2\',',
  '  info: \'#3B82F6\',',
  '  infoLight: \'#DBEAFE\',',
  '  purple: \'#7C3AED\',',
  '  purpleLight: \'#EDE9FE\',',
  '',
  '  white: \'#FFFFFF\',',
  '  black: \'#000000\',',
  '',
  '  present: \'#10B981\',',
  '  absent: \'#EF4444\',',
  '  holiday: \'#F59E0B\',',
  '',
  '  approved: \'#10B981\',',
  '  rejected: \'#EF4444\',',
  '  pending: \'#F59E0B\',',
  '',
  '  drawerBg: \'#0D47A1\',',
  '  drawerText: \'#FFFFFF\',',
  '  drawerIcon: \'#90CAF9\',',
  '};',
  '',
  'export const darkColors = {',
  '  primary: \'#90CAF9\',',
  '  primaryDark: \'#42A5F5\',',
  '  primaryLight: \'#0D47A1\',',
  '  accent: \'#FFB300\',',
  '  background: \'#121212\',',
  '  card: \'#1E1E1E\',',
  '  surface: \'#1E1E1E\',',
  '',
  '  textPrimary: \'#E0E0E0\',',
  '  textSecondary: \'#AAB4BE\',',
  '  textLight: \'#757575\',',
  '',
  '  border: \'#333333\',',
  '  divider: \'#2C2C2C\',',
  '',
  '  success: \'#34D399\',',
  '  successLight: \'#064E3B\',',
  '  warning: \'#FBBF24\',',
  '  warningLight: \'#78350F\',',
  '  danger: \'#F87171\',',
  '  dangerLight: \'#7F1D1D\',',
  '  info: \'#60A5FA\',',
  '  infoLight: \'#1E3A8A\',',
  '  purple: \'#A78BFA\',',
  '  purpleLight: \'#4C1D95\',',
  '',
  '  white: \'#121212\',',
  '  black: \'#E0E0E0\',',
  '',
  '  present: \'#34D399\',',
  '  absent: \'#F87171\',',
  '  holiday: \'#FBBF24\',',
  '',
  '  approved: \'#34D399\',',
  '  rejected: \'#F87171\',',
  '  pending: \'#FBBF24\',',
  '',
  '  drawerBg: \'#1E1E1E\',',
  '  drawerText: \'#E0E0E0\',',
  '  drawerIcon: \'#90CAF9\',',
  '};',
  '',
  'export const colors = lightColors;'
].join('\n');
fs.writeFileSync('src/theme/colors.ts', content, 'utf8');

