import React from 'react';
import { ScrollView, Text, View, StyleSheet, Linking, TouchableOpacity } from 'react-native';
import { Stack } from 'expo-router';
import { useTheme } from '../src/context/ThemeContext';
import { spacing, fontSize, borderRadius } from '../src/theme/spacing';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';

export default function PrivacyPolicyScreen() {
  const { colors, isDark } = useTheme();
  const styles = getStyles(colors);
  const router = useRouter();

  const handleLink = (url: string) => {
    Linking.openURL(url);
  };

  return (
    <>
      <Stack.Screen 
        options={{ 
          title: 'Privacy Policy',
          headerShown: true, 
          headerStyle: { backgroundColor: colors.background },
          headerTintColor: colors.textPrimary,
          headerLeft: () => (
            <TouchableOpacity onPress={() => router.back()} style={{ marginLeft: 8 }}>
              <Ionicons name="arrow-back" size={24} color={colors.textPrimary} />
            </TouchableOpacity>
          )
        }} 
      />
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        <Text style={styles.title}>Privacy Policy</Text>
        <Text style={styles.text}>Last updated: March 25, 2026</Text>
        
        <Text style={styles.text}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </Text>
        
        <Text style={styles.text}>
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </Text>

        <Text style={styles.h2}>Interpretation and Definitions</Text>
        
        <Text style={styles.h3}>Interpretation</Text>
        <Text style={styles.text}>
          The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </Text>
        
        <Text style={styles.h3}>Definitions</Text>
        <Text style={styles.text}>For the purposes of this Privacy Policy:</Text>
        
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Account</Text> means a unique account created for You to access our Service or parts of our Service.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Affiliate</Text> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Application</Text> refers to VidDarpan, the software program provided by the Company.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Company</Text> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to VidDarpan.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Country</Text> refers to: Uttar Pradesh, India</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Device</Text> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Personal Data</Text> (or "Personal Information") is any information that relates to an identified or identifiable individual.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Service</Text> refers to the Application.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Service Provider</Text> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>Usage Data</Text> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>You</Text> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
        </View>

        <Text style={styles.h2}>Collecting and Using Your Personal Data</Text>
        
        <Text style={styles.h3}>Types of Data Collected</Text>
        
        <Text style={styles.h4}>Personal Data</Text>
        <Text style={styles.text}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </Text>
        
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>Email address</Text>
          <Text style={styles.bulletItem}>First name and last name</Text>
          <Text style={styles.bulletItem}>Phone number</Text>
        </View>

        <Text style={styles.h4}>Usage Data</Text>
        <Text style={styles.text}>Usage Data is collected automatically when using the Service.</Text>
        <Text style={styles.text}>
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </Text>
        <Text style={styles.text}>
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </Text>
        
        <Text style={styles.h4}>Information Collected while Using the Application</Text>
        <Text style={styles.text}>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>Pictures and other information from your Device's camera and photo library</Text>
        </View>
        <Text style={styles.text}>
          We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
        </Text>
        <Text style={styles.text}>You can enable or disable access to this information at any time, through Your Device settings.</Text>

        <Text style={styles.h3}>Use of Your Personal Data</Text>
        <Text style={styles.text}>The Company may use Personal Data for the following purposes:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}><Text style={styles.bold}>To provide and maintain our Service</Text>, including to monitor the usage of our Service.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>To manage Your Account:</Text> to manage Your registration as a user of the Service.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>For the performance of a contract:</Text> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>To contact You:</Text> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>To provide You</Text> with news, special offers, and general information about other goods, services and events which We offer.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>To manage Your requests:</Text> To attend and manage Your requests to Us.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>For business transfers:</Text> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</Text>
        </View>
        
        <Text style={styles.text}>We may share Your Personal Data in the following situations:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}><Text style={styles.bold}>With Service Providers:</Text> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>For business transfers:</Text> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>With Affiliates:</Text> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>With business partners:</Text> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>With other users:</Text> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</Text>
          <Text style={styles.bulletItem}><Text style={styles.bold}>With Your consent:</Text> We may disclose Your Personal Data for any other purpose with Your consent.</Text>
        </View>

        <Text style={styles.h3}>Retention of Your Personal Data</Text>
        <Text style={styles.text}>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
        </Text>

        <Text style={styles.h3}>Transfer of Your Personal Data</Text>
        <Text style={styles.text}>
          Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
        </Text>

        <Text style={styles.h3}>Delete Your Personal Data</Text>
        <Text style={styles.text}>
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        </Text>

        <Text style={styles.h3}>Disclosure of Your Personal Data</Text>
        <Text style={styles.text}>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
        </Text>

        <Text style={styles.h3}>Security of Your Personal Data</Text>
        <Text style={styles.text}>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </Text>

        <Text style={styles.h2}>Children's Privacy</Text>
        <Text style={styles.text}>
          Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
        </Text>

        <Text style={styles.h2}>Links to Other Websites</Text>
        <Text style={styles.text}>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </Text>

        <Text style={styles.h2}>Changes to this Privacy Policy</Text>
        <Text style={styles.text}>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
        </Text>

        <Text style={styles.h2}>Contact Us</Text>
        <Text style={styles.text}>If you have any questions about this Privacy Policy, You can contact us:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>
            By email: <Text style={styles.link} onPress={() => handleLink('mailto:hello@viddarpan.com')}>hello@viddarpan.com</Text>
          </Text>
          <Text style={styles.bulletItem}>
            By visiting this page on our website: <Text style={styles.link} onPress={() => handleLink('https://www.viddarpan.com/')}>https://www.viddarpan.com/</Text>
          </Text>
        </View>
      </ScrollView>
    </>
  );
}

const getStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: spacing.lg,
    paddingBottom: 40,
  },
  title: {
    fontSize: fontSize.xl + 4,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  h2: {
    fontSize: fontSize.lg + 2,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  h3: {
    fontSize: fontSize.lg,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginTop: spacing.lg,
    marginBottom: spacing.xs,
  },
  h4: {
    fontSize: fontSize.md + 2,
    fontWeight: 'bold',
    color: colors.textSecondary,
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  text: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
    lineHeight: 24,
    marginBottom: spacing.md,
  },
  bold: {
    fontWeight: 'bold',
  },
  bulletList: {
    marginVertical: spacing.sm,
    paddingLeft: spacing.md,
  },
  bulletItem: {
    fontSize: fontSize.md,
    color: colors.textPrimary,
    lineHeight: 24,
    marginBottom: spacing.xs,
  },
  link: {
    color: colors.primary,
    textDecorationLine: 'underline',
  }
});
