const fs = require('fs');

const contextArr = [
  'import React, { createContext, useContext, useState, useEffect } from \'react\';',
  'import AsyncStorage from \'@react-native-async-storage/async-storage\';',
  'import { lightColors, darkColors } from \'../theme/colors\';',
  '',
  'type ThemeContextType = {',
  '  isDark: boolean;',
  '  colors: typeof lightColors;',
  '  toggleTheme: () => void;',
  '  setTheme: (dark: boolean) => void;',
  '};',
  '',
  'const ThemeContext = createContext<ThemeContextType | undefined>(undefined);',
  'const THEME_STORAGE_KEY = \'@app_theme_mode\';',
  '',
  'export const ThemeProvider = ({ children }: { children: React.ReactNode }) => {',
  '  const [isDark, setIsDark] = useState(false); // Default to light mode',
  '',
  '  useEffect(() => {',
  '    // Load saved theme preference on start',
  '    const loadTheme = async () => {',
  '      try {',
  '        const savedTheme = await AsyncStorage.getItem(THEME_STORAGE_KEY);',
  '        if (savedTheme !== null) {',
  '          setIsDark(savedTheme === \'dark\');',
  '        }',
  '      } catch (e) {',
  '        console.error(\'Failed to load theme preference\', e);',
  '      }',
  '    };',
  '    loadTheme();',
  '  }, []);',
  '',
  '  const toggleTheme = async () => {',
  '    const newDarkMode = !isDark;',
  '    setIsDark(newDarkMode);',
  '    try {',
  '      await AsyncStorage.setItem(THEME_STORAGE_KEY, newDarkMode ? \'dark\' : \'light\');',
  '    } catch (e) {',
  '      console.error(\'Failed to save theme preference\', e);',
  '    }',
  '  };',
  '',
  '  const setTheme = async (dark: boolean) => {',
  '    setIsDark(dark);',
  '    try {',
  '      await AsyncStorage.setItem(THEME_STORAGE_KEY, dark ? \'dark\' : \'light\');',
  '    } catch (e) {',
  '      console.error(\'Failed to save theme preference\', e);',
  '    }',
  '  };',
  '',
  '  const colors = isDark ? darkColors : lightColors;',
  '',
  '  return (',
  '    <ThemeContext.Provider value={{ isDark, colors, toggleTheme, setTheme }}>',
  '      {children}',
  '    </ThemeContext.Provider>',
  '  );',
  '};',
  '',
  'export const useTheme = () => {',
  '  const context = useContext(ThemeContext);',
  '  if (!context) throw new Error(\'useTheme must be used within ThemeProvider\');',
  '  return context;',
  '};'
];

fs.writeFileSync('src/context/ThemeContext.tsx', contextArr.join('\n'), 'utf8');
console.log('Updated ThemeContext successfully.');

